spring.application.name=java-compiler-backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/java_compiler_db;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASS:password}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

jwt.secret=${JWT_SECRET:8bf20a9a8342f06f7cf91c1072d627c2fde978c430932bcb344fa0e43d939e6a256a24137c4627255152a5a544c92e9e9842f13ff5a666ac5be9fca0d1a4ee85}

spring.mail.port=${MAIL_PORT:25}
spring.mail.username=${MAIL_USER:user}
spring.mail.password=${MAIL_PASS:pass}