spring.application.name=java-compiler-backend
server.port=8000

spring.datasource.url=jdbc:h2:file:./data/admin_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:yashwanthvarma.simats@gmail.com}
spring.mail.password=${SMTP_PASSWORD:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=${JWT_SECRET:8bf20a9a8342f06f7cf91c1072d627c2fde978c430932bcb344fa0e43d939e6a256a24137c4627255152a5a544c92e9e9842f13ff5a666ac5be9fca0d1a4ee85}